version: '3.8'

services:
  # Application container
  mingle:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Database
      MONGO_URI: ${MONGO_URI}
      
      # JWT Secret
      JWT_SECRET: ${JWT_SECRET}
      
      # OAuth v2 Google Credentials
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      
      # Session Secret
      SESSION_SECRET: ${SESSION_SECRET}
      
      # Application Config
      NODE_ENV: production
    depends_on:
      - mongo
  
  # MongoDB container
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

# Named volume for data persistence
volumes:
  mongo_data: