apiVersion: apps/v1
kind: Deployment
metadata:
  name: mingle-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mingle-api
  template:
    metadata:
      labels:
        app: mingle-api
    spec:
      containers:
        - name: mingle-api
          image: hish5296/mingle-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mingle-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mingle-secrets
                  key: JWT_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: mingle-secrets
                  key: SESSION_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mingle-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mingle-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: mingle-secrets
                  key: GOOGLE_CALLBACK_URL
---
# Internal Service
apiVersion: v1
kind: Service
metadata:
  name: mingle-service
spec:
  type: ClusterIP
  selector:
    app: mingle-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
# HTTPS Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mingle-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - mingle.<EXTERNAL_IP>.sslip.io # Change to current external IP of Load Balancer (nginx ingress controller)
      secretName: mingle-tls-secret
  rules:
    - host: mingle.<EXTERNAL_IP.sslip.io # Change to current external IP of Load Balancer (nginx ingress controller)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mingle-service
                port:
                  number: 80